#!/bin/bash
sudo apt update
sudo apt upgrade

sudo apt install g++ python3 btop clangd-20 git curl wget
sudo snap install nvim --classic
sudo snap install telegram-desktop
sudo snap install bobrossquotes
sudo apt install steam lutris
git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git
bash <(curl https://i.hiddify.com/release)

sudo apt install luarocks
sudo apt install zsh
chsh -s $(which zsh)
touch "$HOME/.cache/zshhistory"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc

sudo snap install jetbrains-mono --classic
fc-cache -fv
